services:
  studio:
    container-name: supabase-studio
    build:
      context: ./connexpay
      dockerfile: services/supabase-studio/Dockerfile

  kong:
    container-name: supabase-kong
    build:
      context: ./connexpay
      dockerfile: services/supabase-kong/Dockerfile

  auth:
    container-name: supabase-auth
    build:
      context: ./connexpay
      dockerfile: services/supabase-auth/Dockerfile

  rest:
    image:

  realtime:
    image:

  storage:
    image:

  imgproxy:
    image:

  meta:
    image:

  functions:
    image:

  analytics:
    container-name: supabase-analytics
    build:
      context: ./connexpay
      dockerfile: services/supabase-analytics/Dockerfile

  db:
    image:

  vector:
    image:

  supavisor:
    image:
