services:
  flowise:
    container_name: flowise
    build:
      context: ./connexpay
      dockerfile: services/flowise/Dockerfile
    ports:
      - 127.0.0.1:3001:3001

  open-webui:
    image:
    ports:
      - 127.0.0.1:8080:8080

  n8n:
    container_name: n8n
    build:
      context: ./connexpay
      dockerfile: services/n8n/Dockerfile
    ports:
      - 127.0.0.1:5678:5678

  n8n-import:
    container_name: n8n-import
    build:
      context: ./connexpay
      dockerfile: services/n8n-import/Dockerfile

  qdrant:
    image:
    ports:
      - 127.0.0.1:6333:6333
      - 127.0.0.1:6334:6334

  neo4j:
    image:
    ports:
      - 127.0.0.1:7473:7473
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687

  caddy:
    container_name: caddy
    build:
      context: ./connexpay
      dockerfile: services/caddy/Dockerfile

  langfuse-worker:
    container_name: langfuse-worker
    build:
      context: ./connexpay
      dockerfile: services/langfuse-worker/Dockerfile
    ports:
      - 127.0.0.1:3030:3030

  langfuse-web:
    container_name: langfuse-web
    build:
      context: ./connexpay
      dockerfile: services/langfuse-web/Dockerfile
    ports:
      - 127.0.0.1:3000:3000

  clickhouse:
    container_name: clickhouse
    build:
      context: ./connexpay
      dockerfile: services/clickhouse/Dockerfile
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009

  minio:
    image:
    ports:
      - 127.0.0.1:9010:9000
      - 127.0.0.1:9011:9001

  postgres:
    image:
    ports:
      - 127.0.0.1:5433:5432

  redis:
    image:
    ports:
      - 127.0.0.1:6379:6379

  searxng:
    image:
    ports:
      - 127.0.0.1:8081:8080

  ollama:
    image:

  ollama-cpu:
    image:
    ports:
      - 127.0.0.1:11434:11434

  ollama-gpu:
    image:
    ports:
      - 127.0.0.1:11434:11434

  ollama-gpu-amd:
    image:
    ports:
      - 127.0.0.1:11434:11434

  whisper:
    image:
    ports:
      - 127.0.0.1:10101:10101
